name: Deploy to gh-pages

on:
  push:
    branches:
      - master
    paths:
      - 'dist/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Copy files from dist to root
        run: |
          mkdir -p output
          cp -r dist/* output/

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: true